#!/bin/bash
SCRIPT_NAME=$0

function usage {
    echo "usage: $SCRIPT_NAME <app_dir>"
    echo "  -app_dir                    name of the app to build: redis, iperf3,memcached and ping"
    echo "  -h/--help                   display this help message."
    exit 1
}

if [ "$#" -ne 1 ];
then
    echo "Illegal number of parameters!"
    usage
fi

if [[ ! -d "$1" ]];
then
    echo "Not supported app: $1."
    usage
fi

if [[ ! -d "utils" ]];
then
    echo "Utils directory not found! Make sure you are running the script from the examples' home directory."
    exit 1
fi

case $1 in
    "iperf3")
        echo "Building images for the iPerf3 application..."
        docker build -f iperf3/iperf3-client/Dockerfile -t kollaps/iperf3-client:1.0 iperf3/iperf3-client
        docker build -f iperf3/iperf3-server/Dockerfile -t kollaps/iperf3-server:1.0 iperf3/iperf3-server
        ;;
    "iperf3network")
        echo "Building images for the iPerf3network application..."
        docker build -f iperf3network/Dockerfile -t kollaps/iperf3-network:1.0 iperf3network/
        ;;

    "memcached")
        echo "Building images for the memcacehd application..."
        docker build -f memcached/memtier-client/Dockerfile -t kollaps/memtier-client:1.0 memcached/memtier-client
        docker build -f memcached/memcached-server/Dockerfile -t kollaps/memcached-server:1.0 memcached/memcached-server
        ;;

    "redis")
        echo "Building images for the Redis application..."
        ;;
    "ping")
        echo "Building images for the ping application..."
        docker build -f ping/Dockerfile -t kollaps/ping-client:1.0 ping
        ;;

    *)
        echo "Not supported app: $1."
        usage
        ;;
esac

echo "Building helper images..."
docker build -f utils/dashboard/Dockerfile -t kollaps/dashboard:1.0 utils/dashboard/
