[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emulationcore= {path = "../emulationcore/"}
async-std = "1.7.0"
roxmltree = "0.14.1"